### ISSUE TITLE
Add support to avoid ordered pairs

### ISSUE THREAD

**Issue by satreix** [satreix/secret-santa#1]
Merge in https://github.com/underbluewaters/secret-santa/pull/7

**Comment by harman28** [comment]
@satreix Can this be merged? Or do I need to make some changes?

**Comment by satreix** [comment]
Go ahead. 👍

**Comment by harman28** [comment]
@satreix I can't merge myself ¯\_(ツ)_/¯
You'll need to do it, if you're happy with the changes.

**Comment by satreix** [comment]
This is an issue, not some working code. On top of this I moved away from the python implementation a while back. Closing this issue then, for clarity.
